<a href="https://colab.research.google.com/github/yeabwang/tensorflow/blob/main/Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_indexed = tf.constant([3,2,1,4,7,8])

print(tensor_indexed)
print(tensor_indexed[0:4:2])

tf.Tensor([3 2 1 4 7 8], shape=(6,), dtype=int32)
tf.Tensor([3 1], shape=(2,), dtype=int32)


In [ ]:
tf.range(1,4)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
index_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
#print(index_two_d)
print(index_two_d[0:3,0:2])
print(index_two_d[2,1:2])
print(index_two_d[...,1:3])

tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor(
[[2 3]
 [5 6]
 [8 9]], shape=(3, 2), dtype=int32)


In [ ]:
index_three_d = tf.constant([
    [[1,2,3,4],
    [5,6,7,8]],

    [[1,2,3,4],
    [5,6,7,8]],

    [[1,2,3,4],
    [5,6,7,8]]
])

print(index_three_d)
print(index_three_d[0,:,:])

tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]], shape=(3, 2, 4), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
