<a href="https://colab.research.google.com/github/yeabwang/tensorflow/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
# matrix multiplication // not element wise
# For this to happen the number of columns in the first row should be equal to the number of columns in the second row.
#  2x3 and 3x2 - valid
# 2x3 and 2x3 - invalid
# In case of 3d matrix, we are going to do the multiplication the first batch of the first matrix to the first batch of the second matrix

x1 = tf.constant([[1,2,0],
                [3,5,-1]])
x2 = tf.constant([[1,2,0],
                 [3,5,-1],
                [3,5,-1]])

tf.linalg.matmul(x1,x2)
print(x1@x2)
tf.linalg.matmul(x1,x2,transpose_b=False, transpose_a = False,adjoint_a=False, a_is_sparse=False,output_type=None, name=None)


tf.Tensor(
[[ 7 12 -2]
 [15 26 -4]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 12, -2],
       [15, 26, -4]], dtype=int32)>

In [ ]:
tf.transpose(x1)
tf.transpose(x2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  3,  3],
       [ 2,  5,  5],
       [ 0, -1, -1]], dtype=int32)>