<a href="https://colab.research.google.com/github/yeabwang/tensorflow/blob/main/TensorflowFunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
#Expanding dimensions -  Expanding a tensor adds dimensions of size 1 to the tensor.
#This is useful for broadcasting, which allows you to perform element-wise operations on tensors of different shapes.

x1 = tf.constant([
    [[2,6,4,2],
    [2,-2,2,3],
    [1,5,4,0]],

    [[2,6,4,2],
    [2,-2,2,3],
    [1,5,4,0]]
])

print("Original Tensor" , x1.shape)
expanded_tensor = tf.expand_dims(x1,axis=0) #will add one new dimension like changing three d to four d
#print(expanded_tensor)
print("Expanded tensor",expanded_tensor.shape)

Original Tensor (2, 3, 4)
Expanded tensor (1, 2, 3, 4)


In [ ]:
# Squeezing or removing dimension - removes dimensions with size 1. This is typically used when you want to eliminate unnecessary dimensions that do not contribute to the tensor’s data, making it more compact.

print("Expanded Tensor" , expanded_tensor.shape)
squeezed_tensor = tf.squeeze(expanded_tensor, axis=0) # We can only squeeze out the extra axis we expanded
# print(squeezed_tensor)
print("Squeezed Tensor" , squeezed_tensor.shape)

Expanded Tensor (1, 2, 3, 4)
Squeezed Tensor (2, 3, 4)


In [ ]:
# Reshaping tensor - the operation of changing the shape or dimensionality of the tensor without altering its data.
# We can only reshape it to a shape that match our original shape total number.
# If we have (3,4) we can only reshape it to (1,12), and (2,6) since we have to keep the 12 toatl numbers

x1 = tf.constant([
    [2,6,4,2],
    [2,-2,2,3],
    [1,5,4,0]
])
print(x1.shape)

reshaped = tf.reshape(x1,shape=(2,6))
print(reshaped.shape)

(3, 4)
(2, 6)


In [29]:
# Concatinating tensors
x1 = tf.constant([
    [2,6,4,2],
    [2,-2,2,3],
    [1,5,4,0]
])

x2 = tf.constant([

    [3,-1,7,4],
    [6,2,-5,9],
    [-2,8,0,1]
])

concatinated = tf.concat([x1,x2],axis=1) # axis has to be between 0 and 1, 0 row wise, 1 column wise
# When the axis is 1 we fix the row wise and we will add the columns of the two matrix
print(concatinated)
concatinated = tf.concat([x1,x2],axis=0)
# When the axis is 0 we fix the columns and we add up the rows
print(concatinated)

tf.Tensor(
[[ 2  6  4  2  3 -1  7  4]
 [ 2 -2  2  3  6  2 -5  9]
 [ 1  5  4  0 -2  8  0  1]], shape=(3, 8), dtype=int32)
tf.Tensor(
[[ 2  6  4  2]
 [ 2 -2  2  3]
 [ 1  5  4  0]
 [ 3 -1  7  4]
 [ 6  2 -5  9]
 [-2  8  0  1]], shape=(6, 4), dtype=int32)


In [37]:
# stack - stacks a list of tensors along a new dimension. It creates a new dimension and appends the tensors along this dimension, resulting in a tensor with a higher rank.

x1 = tf.constant([
    [2,6,4,2],
    [2,-2,2,3],
    [1,5,4,0]
])
x2 = tf.constant([

    [3,-1,7,4],
    [6,2,-5,9],
    [-2,8,0,1]
])

stacking_rows = tf.stack([x1,x2], axis = 0) # When you stack tensors along axis=0, a new dimension is added at the beginning (the first axis).
print(stacking_rows, "\n")

stacking_perrows = tf.stack([x1,x2], axis = 1) # When you stack along axis=1, the new dimension is added between the first and second axes of the tensors.
print(stacking_perrows, "\n")

stacking_col =  tf.stack([x1,x2], axis = -1) # When you stack along axis=-1, you're stacking along the last dimension. This essentially means you're adding a new dimension to the end of the tensor.
print(stacking_col, "\n")


tf.Tensor(
[[[ 2  6  4  2]
  [ 2 -2  2  3]
  [ 1  5  4  0]]

 [[ 3 -1  7  4]
  [ 6  2 -5  9]
  [-2  8  0  1]]], shape=(2, 3, 4), dtype=int32) 

tf.Tensor(
[[[ 2  6  4  2]
  [ 3 -1  7  4]]

 [[ 2 -2  2  3]
  [ 6  2 -5  9]]

 [[ 1  5  4  0]
  [-2  8  0  1]]], shape=(3, 2, 4), dtype=int32) 

tf.Tensor(
[[[ 2  3]
  [ 6 -1]
  [ 4  7]
  [ 2  4]]

 [[ 2  6]
  [-2  2]
  [ 2 -5]
  [ 3  9]]

 [[ 1 -2]
  [ 5  8]
  [ 4  0]
  [ 0  1]]], shape=(3, 4, 2), dtype=int32) 

