<a href="https://colab.research.google.com/github/yeabwang/tensorflow/blob/main/tensormath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tf_abs = tf.abs([-2])
print(tf_abs)

tf.Tensor([2], shape=(1,), dtype=int32)


In [ ]:
tf.abs(tf.constant([-0.2]))

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.2], dtype=float32)>

In [ ]:
#tensor with complex numbers

x_abs_complex = tf.constant([-2.30+4.8j, -9.0+3.2j])
tf.abs(x_abs_complex)
tf.sqrt(x_abs_complex)

<tf.Tensor: shape=(2,), dtype=complex128, numpy=array([1.22934807+1.95225426j, 0.52533949+3.04564961j])>

In [ ]:
#element wise addition, multiplication, subs and div

x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,4])
tf.add(x1,x2)
tf.subtract(x1,x2)
tf.multiply(x1,x2)
tf.divide(x1,x2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([6, 7, 8, 9], dtype=int32)>

In [ ]:
#Handling null or infinity values
x1 = tf.constant([1,2,3,4])
x2 = tf.constant([0])
tf.math.divide_no_nan(x1,x2)


<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0., 0., 0., 0.])>

In [ ]:
# Max of two tensors element wise
x1 = tf.constant([12,20,3,4])
x2 = tf.constant([5,6,7,41])

tf.math.maximum(x1,x2,name=None)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12, 20,  7, 41], dtype=int32)>

In [ ]:
# Arg max return the index of the max
x1 = tf.constant([
    [12,20,3,4],
    [32,1,33,8]
    ])
x2 = tf.constant([5,6,7,41])
print(tf.math.argmax(x2))
print(tf.math.argmax(x1))
print(tf.math.argmax(x1,0)) # the comparision will be done column wise # 0 is called axis
print(tf.math.argmax(x1,1)) # the comparision will be done row wise

tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([1 0 1 1], shape=(4,), dtype=int64)
tf.Tensor([1 0 1 1], shape=(4,), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int64)


In [ ]:
# Arg min return the index of the maminx
x1 = tf.constant([
    [12,20,3,4],
    [32,1,32,8]
    ])
x2 = tf.constant([5,6,7,41])
print(tf.math.argmin(x2))
print(tf.math.argmin(x1))

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([0 1 0 0], shape=(4,), dtype=int64)


In [ ]:
x1 = tf.constant([2,3,4,5])
x2 = tf.constant([2,3,4,5])
tf.pow(x1,x2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([   4,   27,  256, 3125], dtype=int32)>

In [ ]:
x1 = tf.constant([
    [12,20,3,4],
    [32,1,32,8]
    ])

print(tf.math.reduce_sum(x1,axis=0, keepdims=False)) #here we are saying lets fix the row(by putting 0) and the operation will happen column wise
print(tf.math.reduce_sum(x1,axis=1, keepdims=True))

tf.Tensor([44 21 35 12], shape=(4,), dtype=int32)
tf.Tensor(
[[39]
 [73]], shape=(2, 1), dtype=int32)


In [ ]:
x1 = tf.constant([
    [12,20,3,4],
    [32,1,32,8]
    ])

print(tf.math.reduce_max(x1,axis=None, keepdims=False))

tf.Tensor(32, shape=(), dtype=int32)


In [ ]:
#Sigmoid zFunction
# The foprmula of sigmoid function is sigmoid(x) = y = 1/1+exp(-x) for all x (-inf, inf)
# The output will be between 0 amd 1

x = tf.constant([
    [20, 32, 1.2,6,2],
    [0.3,0.45,1.4,1.6,3]
])

tf.math.sigmoid(x)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1.        , 1.        , 0.7685247 , 0.99752736, 0.8807971 ],
       [0.57444245, 0.6106392 , 0.80218387, 0.8320184 , 0.95257413]],
      dtype=float32)>

In [ ]:
#Top k will check our matrix and return the top k elements by analysing row wise

x = tf.constant([
    [20, 32, 1.2,6,2],
    [0.3,0.45,1.4,1.6,3]
])

tf.math.top_k(x,k=2,sorted=True)

TopKV2(values=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[32. , 20. ],
       [ 3. ,  1.6]], dtype=float32)>, indices=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [4, 3]], dtype=int32)>)