<a href="https://colab.research.google.com/github/yeabwang/tensorflow/blob/main/TensorflowFunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [ ]:
#Expanding dimensions -  Expanding a tensor adds dimensions of size 1 to the tensor.
#This is useful for broadcasting, which allows you to perform element-wise operations on tensors of different shapes.

x1 = tf.constant([
    [[2,6,4,2],
    [2,-2,2,3],
    [1,5,4,0]],

    [[2,6,4,2],
    [2,-2,2,3],
    [1,5,4,0]]
])

print("Original Tensor" , x1.shape)
expanded_tensor = tf.expand_dims(x1,axis=0) #will add one new dimension like changing three d to four d
#print(expanded_tensor)
print("Expanded tensor",expanded_tensor.shape)

Original Tensor (2, 3, 4)
Expanded tensor (1, 2, 3, 4)


In [ ]:
# Squeezing or removing dimension - removes dimensions with size 1. This is typically used when you want to eliminate unnecessary dimensions that do not contribute to the tensor’s data, making it more compact.

print("Expanded Tensor" , expanded_tensor.shape)
squeezed_tensor = tf.squeeze(expanded_tensor, axis=0) # We can only squeeze out the extra axis we expanded
# print(squeezed_tensor)
print("Squeezed Tensor" , squeezed_tensor.shape)

Expanded Tensor (1, 2, 3, 4)
Squeezed Tensor (2, 3, 4)


In [ ]:
# Reshaping tensor - the operation of changing the shape or dimensionality of the tensor without altering its data.
# We can only reshape it to a shape that match our original shape total number.
# If we have (3,4) we can only reshape it to (1,12), and (2,6) since we have to keep the 12 toatl numbers

x1 = tf.constant([
    [2,6,4,2],
    [2,-2,2,3],
    [1,5,4,0]
])
print(x1.shape)

reshaped = tf.reshape(x1,shape=(2,6))
print(reshaped.shape)

(3, 4)
(2, 6)


In [29]:
# Concatinating tensors
x1 = tf.constant([
    [2,6,4,2],
    [2,-2,2,3],
    [1,5,4,0]
])

x2 = tf.constant([

    [3,-1,7,4],
    [6,2,-5,9],
    [-2,8,0,1]
])

concatinated = tf.concat([x1,x2],axis=1) # axis has to be between 0 and 1, 0 row wise, 1 column wise
# When the axis is 1 we fix the row wise and we will add the columns of the two matrix
print(concatinated)
concatinated = tf.concat([x1,x2],axis=0)
# When the axis is 0 we fix the columns and we add up the rows
print(concatinated)

tf.Tensor(
[[ 2  6  4  2  3 -1  7  4]
 [ 2 -2  2  3  6  2 -5  9]
 [ 1  5  4  0 -2  8  0  1]], shape=(3, 8), dtype=int32)
tf.Tensor(
[[ 2  6  4  2]
 [ 2 -2  2  3]
 [ 1  5  4  0]
 [ 3 -1  7  4]
 [ 6  2 -5  9]
 [-2  8  0  1]], shape=(6, 4), dtype=int32)


In [37]:
# stack - stacks a list of tensors along a new dimension. It creates a new dimension and appends the tensors along this dimension, resulting in a tensor with a higher rank.

x1 = tf.constant([
    [2,6,4,2],
    [2,-2,2,3],
    [1,5,4,0]
])
x2 = tf.constant([

    [3,-1,7,4],
    [6,2,-5,9],
    [-2,8,0,1]
])

stacking_rows = tf.stack([x1,x2], axis = 0) # When you stack tensors along axis=0, a new dimension is added at the beginning (the first axis).
print(stacking_rows, "\n")

stacking_perrows = tf.stack([x1,x2], axis = 1) # When you stack along axis=1, the new dimension is added between the first and second axes of the tensors.
print(stacking_perrows, "\n")

stacking_col =  tf.stack([x1,x2], axis = -1) # When you stack along axis=-1, you're stacking along the last dimension. This essentially means you're adding a new dimension to the end of the tensor.
print(stacking_col, "\n")


tf.Tensor(
[[[ 2  6  4  2]
  [ 2 -2  2  3]
  [ 1  5  4  0]]

 [[ 3 -1  7  4]
  [ 6  2 -5  9]
  [-2  8  0  1]]], shape=(2, 3, 4), dtype=int32) 

tf.Tensor(
[[[ 2  6  4  2]
  [ 3 -1  7  4]]

 [[ 2 -2  2  3]
  [ 6  2 -5  9]]

 [[ 1  5  4  0]
  [-2  8  0  1]]], shape=(3, 2, 4), dtype=int32) 

tf.Tensor(
[[[ 2  3]
  [ 6 -1]
  [ 4  7]
  [ 2  4]]

 [[ 2  6]
  [-2  2]
  [ 2 -5]
  [ 3  9]]

 [[ 1 -2]
  [ 5  8]
  [ 4  0]
  [ 0  1]]], shape=(3, 4, 2), dtype=int32) 



In [8]:
# Paddings - Padding is the process of adding extra values around a tensor (which can be thought of as an array or matrix).
# Usually we add extra zeros, but we can also addd any cosntants.
# Needed to make all inputs we are dealing with has a same size, and also if we are dealing with images it makes sure that we are covering the edges properly without losing the informations from the border.

#tf.pad(tensor, paddings, mode="CONSTANT", constant_values=0, name=None)

# padding -  will be put based on the dimension we have if we have (x,y) dimension we will put how much padding
# are we going to give to x and y using ([1,1], [2,2]) this means give add one row above and one row below and two on the left and two on the right .

#padding mode - it specify how the padding values are filled.
# -   CONSTANT - The padding will be filled with constants.
# - REFLECT - The values will be taken and mirrored from the edge.
# - SYMMETRIC - Its similar to the reflect option but when its reflected it includes the boundary values.
# EDGE - Filling with repeated values of the edge.

# constant_value - the value we are going to use if we chose the padding mode as a constant.

x1 = tf.constant([
    [2,6,4,2],
    [2,-2,2,3],
    [1,5,4,1]
])

print(x1.shape)

padded = tf.pad(x1,([1,1],[2,2]), mode="CONSTANT", constant_values= 0)
print(padded)
print(padded.shape)



(3, 4)
tf.Tensor(
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  2  6  4  2  0  0]
 [ 0  0  2 -2  2  3  0  0]
 [ 0  0  1  5  4  1  0  0]
 [ 0  0  0  0  0  0  0  0]], shape=(5, 8), dtype=int32)
(5, 8)


In [19]:
# Gather  operation that allows you to select specific elements from a tensor based on indices. It helps in gathering slices or subsets of data from a tensor along a specified axis.
#It can be particularly useful when you want to extract certain rows, columns, or slices from a multi-dimensional tensor.

# tf.gather(
#     params, - the matrix which we are be working with.
#     indices, - the items we are planning to gather (0,2) - we are saying we are gathering the 0th and 2nd row.
#     axis=None, - the axis we are going to work in, 0 means across thr rows and 1 means across the columns.
#     batch_dims=0, - the batch dimension we are working on
#     name=None
# )

x1 = tf.constant([
    [2,6,4,2],
    [2,-2,2,3],
    [1,5,4,1]
])

indices_1 = [0,1,2]
indices_2 = [1,2]

gathered = tf.gather(x1, indices_1, axis=0, batch_dims=0)
print(gathered)
gathered = tf.gather(x1, indices_2, axis=1, batch_dims=0)
print(gathered)


tf.Tensor(
[[ 2  6  4  2]
 [ 2 -2  2  3]
 [ 1  5  4  1]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 6  4]
 [-2  2]
 [ 5  4]], shape=(3, 2), dtype=int32)


In [22]:
# Gather-nd 0 - its the more advanced version of tf.gather and allow us to gather values from multi-dimension indices.
# This is essential when it comes to extracting values from multiple specific positions.
# The key element here is high flexability.

# tf.gather_nd(
#     params, - tensor from which to gather values.
#     indices, - A tensor containing the multi-dimensional indices used to gather values.
#     name=None
# )

params = tf.constant([
    [[1, 2, 3],
     [4, 5, 6],
      [7, 8, 9]],

     [[10, 11, 12],
     [13, 14, 15],
      [16, 17, 18]]

    ])

indices = tf.constant([
    [0, 1, 2],
     [1, 0, 1]])

gathered_nd = tf.gather_nd(params,indices, batch_dims=0)
print(gathered_nd)

tf.Tensor([ 6 11], shape=(2,), dtype=int32)
